version: '3.9'

services:
  frontend:
    build:
      context: ../app
      dockerfile: ../docker/frontend/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ../app:/app
    stdin_open: true
    tty: true
    depends_on:
      - php
      - db
  php:
    build:
      context: ..
      dockerfile: docker/php/Dockerfile
    container_name: php-container
    volumes:
      - ../api:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-container
    volumes:
      - ../api:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - app-network

  db:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
